version: '3'

services:
  akka_test_seeder:
    container_name: akka-test_seeder
    image: akka-test
    ports:
      - 8081:8080
    environment:
      - "JAVA_OPTS=-Dspring.profiles.active=seeder"

  akka_test_non_seeder:
    container_name: akka-test_non_seeder
    image: akka-test
    ports:
      - 8082:8080
    environment:
      - "JAVA_OPTS=-Dspring.profiles.active=non_seeder"
